settings:
  title: 'Macin Status'
  url: 'https://macin.org' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: macin-org # unique identifier
    name: macin.org
    description: 'Read my Blog.'
    url: 'https://macin.org' # URL to fetch
    method: GET
    expectStatus: 200
    followRedirect: false  # should fetch follow redirects, default=false
    linkable: true

  - id: docker-macin-org
    name: docker.macin.org
    description: 'A free node for Docker'
    url: 'https://docker.macin.org'
    method: GET
    expectStatus: 200
    linkable: true

  - id: talk-macin-org
    name: talk.macin.org
    description: 'Read my Blog comments.'
    url: 'https://talk.macin.org/ui#'
    method: GET
    expectStatus: 200
    linkable: true

  - id: gpt-macin-org
    name: gpt.macin.org
    description: 'Use ChatGPT for free.'
    url: 'https://gpt.macin.org'
    method: GET
    expectStatus: 200
    linkable: true
