settings:
  title: 'Macin Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: macin-org # unique identifier
    name: macin.org
    url: 'https://macin.org/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200
    followRedirect: false  # should fetch follow redirects, default=false
    linkable: true

  - id: nas-macin-org
    name: nas.macin.org
    description: 'Built for anything connected to the Internet.'
    url: 'https://nas.macin.org:5001'
    method: GET
    expectStatus: 200
    linkable: true

  - id: docker-macin-org
    name: docker.macin.org
    url: 'https://docker.macin.org'
    method: GET
    expectStatus: 200
    linkable: true

  - id: talk-macin-org
    name: talk.macin.org
    url: 'https://talk.macin.org/ui#'
    method: GET
    expectStatus: 200
    linkable: true

  - id: gcp-macin-org
    name: gcp.macin.org
    url: 'https://gcp.macin.org:2014'
    method: GET
    expectStatus: 200
    linkable: true

  - id: gpt-macin-org
    name: gpt.macin.org
    url: 'https://gpt.macin.org'
    method: GET
    expectStatus: 200
    linkable: true
