settings:
  title: 'Macin Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: macin-org # unique identifier
    name: macin.org
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://macin.org/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: nas-macin-org
    name: nas.macin.org
    description: 'Built for anything connected to the Internet.'
    url: 'https://nas.macin.org:5001'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: docker-macin-org
    name: docker.macin.org
    url: 'https://docker.macin.org'
    method: GET
    expectStatus: 200
